### ISSUE TITLE
Incorrect mapping to lowfat

### ISSUE THREAD

**Issue by jcuenod** [Clear-Bible/macula-hebrew#109]
https://github.com/Clear-Bible/macula-hebrew/blob/c472ed3a9cefc42f6c913c269b2a9661bed39c92/lowfat/01-Gen-006-lowfat.xml#L387C18-L387C18

I'm seeing `Rule="ClCl" Cat="CL"`, but I would have thought lowfat would be lowercase and `Cat` would be `class`. It looks like this mapping has failed for all `ClCl` and `ClCl2`.

**Comment by jonathanrobie** [comment]
Fixed
