### ISSUE TITLE
Low-fat word parts missing

### ISSUE THREAD

**Issue by RobH123** [Clear-Bible/macula-hebrew#116]
From 01-Gen-003-lowfat.xml: (the first occurrence of this systematic problem)

`<wg type="conjuncted-wg" class="cjp" rule="cj2cjp">
                              <w xml:id="o010030050101"
                                 morph="C"
                                 ref="GEN 3:5!10"
                                 lemma="וְ">וִ</w>`

After this entry (which I abbreviated) for Gen 3:5 word 10, the next word is word 11. AFAICS, the rest (the main portion 'הְיִיתֶם֙') of word 10 is missing as word 11 seems correct with two morphemes?

**Comment by jonathanrobie** [comment]
This is an issue I am working on now.  I have recently found ~ 900 places where words are missing or in the wrong place in the current Hebrew lowfat.  I will update here when I have found and fixed the problem.

**Comment by RobH123** [comment]
Yes, it seems that the TSV has it correctly.

**Comment by RobH123** [comment]
Ah, TSV lacks the valuable role info (which can occur in <w> fields but is often in the parent <wg> fields). Oh well...I'll go back to waiting for the repaired lowfat XML.

**Comment by RobH123** [comment]
Ah, thanks for the update. What does 'c' stand for here?\

               <wg class="np" rule="Np-Appos" head="true">
                  <c role="">
                     <w xml:id="o010040220061"
                        morph="Np"
                        pos="noun"
                        after=" "
                        type="proper"
                        ref="GEN 4:22!6"
                        sdbh="007730001001000"
                        stronglemma="תּוּבַל־קַ֫יִן"
                        lexdomain="003001007"
                        coredomain=""
                        unicode="תּ֣וּבַל קַ֔יִן"
                        class="noun"
                        lang="H"
                        lemma="תּוּבַל־קַ֫יִן">תּ֣וּבַל</w>
                     <w xml:id="o010040220071"
                        morph="Np"
                        pos="noun"
                        after=" "
                        type="proper"
                        ref="GEN 4:22!7"
                        sdbh="007730001001000"
                        stronglemma="תּוּבַל־קַ֫יִן"
                        lexdomain="003001007"
                        coredomain=""
                        unicode="תּ֣וּבַל קַ֔יִן"
                        class="noun"
                        lang="H"
                        lemma="תּוּבַל־קַ֫יִן">קַ֔יִן</w>
                  </c>

**Comment by RobH123** [comment]
Closing this issue because I think all the Hebrew word parts are now there.

Created a new issue for the <c> problem: https://github.com/Clear-Bible/macula-hebrew/issues/121
