### ISSUE TITLE
Convert Greek beta encoding to Unicode

### ISSUE THREAD

**Issue by jonathanrobie** [Clear-Bible/macula-hebrew#12]
In annotations.xml, attributes that contain Septuagint Greek are in Beta encoding.  They should be converted to Unicode.

**Comment by klosoter** [comment]
Done using:

`import betacode.conv
from lxml import etree

path = "annotations.xml" #change the path
xml_etree = etree.parse(path)
xml_root = xml_etree.getroot()

for node in xml_root.xpath(f".//*[@Greek]"):
    greek = node.attrib["Greek"]
    node.attrib["Greek"] = betacode.conv.beta_to_uni(greek)
    
xml_etree.write(path, encoding="utf-8")`

Where do I put this file? Or should I just upload the results somewhere?

**Comment by jonathanrobie** [comment]
I think it would be best to:

1. Check the new annotations.xml in as the new`macula-hebrew/sources/Clear/annotations/annotations.xml`
2. Check the code into trees-oshb/py

I didn't know about `betacode.conv`.  Nice.
