### ISSUE TITLE
include Ketiv into Macula-Hebrew ?

### ISSUE THREAD

**Issue by Andley** [Clear-Bible/macula-hebrew#124]
Is it possible to include Ketiv into Macula-Hebrew as well ?

Thanks for your great efforts.

**Comment by jonathanrobie** [comment]
It's possible, but not easy.

We currently have only one syntax tree per sentence.  If we add Ketiv, we would have to have more than one, and we would have to think about how to integrate that into our UI.  Also, we would have to have a thorough syntactic analysis of the Ketiv, which we do not currently have, and for some Ketiv, the syntactic interpretation is uncertain.

So this is a feature that would take work.  If someone competent wants to take that project on, we should talk.

**Comment by Andley** [comment]
understood. Thanks.
