### ISSUE TITLE
Possible missing lemmas in lowfat

### ISSUE THREAD

**Issue by RobH123** [Clear-Bible/macula-hebrew#128]
Not totally sure if these pronominal suffixes are intentionally missing a **lemma** and **stronglemma** entry or not in the lowfat XML files? (Maybe it's intentional???)

46,393 morphemes with no lemmas => 277 unique morphemes_with_missing_lemmas=['א', 'א֒', 'א֙', 'א֩', 'א֮', 'אָ֔ה', 'אָה֙', 'דִ֑י', 'ה', 'ה֑וֹן'
, 'ה֔וֹם', 'ה֔וֹן', 'ה֖וֹן', 'ה֗וֹן', 'ה֙', 'ה֛וֹן', 'ה֜וֹן', 'ה֞וֹן', 'ה֣וֹן', 'ה֩', 'ה֫וּ', 'ה֮', 'הְנָה', 'הִי', 'הִי֙', 'הִי֩', 'הֵ֑ין', 'הֵ֑ן', 'הֵ֔ן', 'הֵ֖ין','הֵ֖ן', 'הֵ֞ן', 'הֵ֣ין', 'הֵ֥ין', 'הֵ֥ן', 'הֵ֨מָה', 'הֵין֙', 'הֵן֙', 'הֶ֑ם', 'הֶ֑ן', 'הֶ֓ם', 'הֶ֔ם', 'הֶ֔ן', 'הֶ֕ם', 'הֶ֖ם', 'הֶ֖ן', 'הֶ֗ם', 'הֶ֗ן', 'הֶ֛ם', 'הֶ֛ן', 'הֶ֜ם','הֶ֜ן', 'הֶ֞ם', 'הֶ֡ם', 'הֶ֣ם', 'הֶ֣ן', 'הֶ֤ם', 'הֶ֤ן', 'הֶ֥ם', 'הֶ֥ן', 'הֶ֧ם', 'הֶ֨ם', 'הֶ֨ן', 'הֶֽם', 'הֶֽן', 'הֶֽנָה', 'הֶם', 'הֶם֒', 'הֶם֙', 'הֶם֩', 'הֶם֮', 'הֶן֙', 'הַם
', 'הָ', 'הָ֒', 'הָ֙', 'הָ֩', 'הָ֮', 'הָא', 'הֹ֑ם', 'הֹ֔ם', 'הֹ֖ם', 'הֹ֗ם', 'הֹ֛ם', 'הֹֽם', 'הּ', 'הּ֒', 'הּ֙', 'הּ֩', 'הּ֮', 'הֶּ֑ם', 'הָּ', 'הֶֽם', 'הֽוֹן', 'הֽוּ', 'הֿ','הׄוּׄ', 'הוֹן֒', 'הוֹן֙', 'הוּ', 'הוּ֒', 'הוּ֙', 'הוּ֩', 'הוּ֮', 'ו', 'ו֒', 'ו֙', 'ו֩', 'ו֮', 'וֹ', 'וֹ֒', 'וֹ֙', 'וֹ֩', 'וֹ֮', 'וּ', 'וּהִי', 'וּךְ', 'וׄ', 'י', 'י֒
', 'י֙', 'י֩', 'י֮', 'יַ', 'יהָ', 'יךְ', 'ך', 'ךְ', 'ךְ֒', 'ךְ֙', 'ךְ֩', 'ךְ֮', 'ךָ', 'ךָ֑', 'ךָ֒', 'ךָ֓', 'ךָ֔', 'ךָ֕', 'ךָ֖', 'ךָ֗', 'ךָ֙', 'ךָ֛', 'ךָ֜', 'ךָ֞', 'ךָ֡','ךָ֣', 'ךָֽ֣', 'ךָ֤', 'ךָ֥', 'ךָ֧', 'ךָ֨', 'ךָ֩', 'ךָ֪', 'ךָ֬', 'ךָ֮', 'ךָֽ', 'ךָּ', 'כ֖וֹן', 'כ֗וֹן', 'כ֣וֹן', 'כ֤וֹן', 'כ֥וֹן', 'כִי', 'כֵה', 'כֶ֑ם', 'כֶ֔ם', 'כֶ֔ן', 'כֶ֕ם','כֶ֖ם', 'כֶ֖ן', 'כֶ֗ם', 'כֶ֛ם', 'כֶ֜ם', 'כֶ֞ם', 'כֶ֡ם', 'כֶ֣ם', 'כֶ֣ן', 'כֶ֤ם', 'כֶ֥ם', 'כֶ֥נָה', 'כֶ֧ם', 'כֶ֨ם', 'כֶ֨נָה֙', 'כֶ֪ם', 'כֶֽם', 'כֶֽן', 'כֶֽנָה', 'כֶם', 'כֶם֒','כֶם֙', 'כֶם֩', 'כֶם֮', 'כֶן֙', 'כָ֔ה', 'כָ֖ה', 'כָ֛ה', 'כָ֜ה', 'כָ֞ה', 'כָ֣ה', 'כָ֤ה', 'כָ֥ה', 'כָ֨ה', 'כָה', 'כָה֙', 'כֹ֖ם', 'כֹ֜ם', 'כֹ֣ם', 'כָּה', 'כָּה֙', 'כוֹן', 'כוֹ
ן֙', 'ם', 'ם֒', 'ם֙', 'ם֩', 'ם֮', 'מוֹ', 'מוֹ֙', 'מוּ', 'ן', 'ן֙', 'נ֛וּ', 'נ֣וּ', 'נ֤וּ', 'נ֥וֹ', 'נ֫וּ', 'נְהָ', 'נְהֽוּ', 'נְהוּ', 'נְהוּ֙', 'נְךָ', 'נְךָּ', 'נְנִי
', 'נִ֔י', 'נִ֕י', 'נִ֖י', 'נִ֛י', 'נִ֣י', 'נִ֤י', 'נִ֥י', 'נִ֧י', 'נִ֨י', 'נִֽי', 'נִי', 'נִי֙', 'נִי֩', 'נִי֮', 'נֶךְ', 'נַ֥נִי', 'נָא', 'נָא֙', 'נָה', 'נָה֙', 'נּ֑וּ','נּ֤וּ', 'נִּי', 'נִּי֒', 'נִּי֙', 'נִּי֩', 'נִּי֮', 'נָּֽה', 'נָּה', 'נָּה֙', 'נָּה֮', 'נּֽוּ', 'נּוּ', 'נּוּ֒', 'נּוּ֙', 'נּוּ֩', 'נׄוּׄ', 'נׄוּׄ֙', 'נוֹ', 'נוּ', 'נוּ֒', 'נוּ֙', 'נוּ֩'
, 'נוּ֮']
Here's an example from Gen 1:12:
                        <wg role="pp" class="pp" rule="PrepNp" head="true">
                           <w xml:id="o010010120071"
                              english="according to"
                              ...
                              **stronglemma="לְ"**
                              strongnumberx="3807a"
                              unicode="לְ"
                              class="prep"
                              lang="H"
                              **lemma="לְ">לְ</w>**
                           <wg class="np" rule="NPofNP" head="true">
                              w xml:id="o010010120072"
                                 english="kind"
                                 ...
                                 **stronglemma="מִין"**
                                 lexdomain="002001"
                                 coredomain=""
                                 sensenumber="1"
                                 greek="γένος"
                                 greekstrong="1085"
                                 strongnumberx="4327"
                                 ...
                                 **lemma="מִין"**
                                 ...
                             **w xml:id="o010010120073"
                                 english="their"
                                 morph="Sp3ms"
                                 pos="suffix"
                                 after=" "
                                 type="pronominal"
                                 ref="GEN 1:12!7"
                                 sdbh="003955001001000"
                                 lexdomain="002001"
                                 coredomain=""
                                 participantref="010010120041"
                                 strongnumberx="1930a"
                                 unicode="ֵ֔הוּ"
                                 class="pron"
                                 lang="H"
                                 gender="masculine"
                                 number="singular"
                                 person="third">הוּ</w>**
                           </wg>
                        </wg>

**Comment by jonathanrobie** [comment]
OSHB uses codes rather than lemmas for pronominal suffixes.  Does this cause problems for you?

**Comment by RobH123** [comment]
Ah, so that's what's happening @jonathanrobie and why. It only caused a problem because they are different from everything else in not having a lemma field, but if it's intentional (and you feel that it's ok as is), that's fine -- I'll figure out where I need to get that equivalent info from. Thanks.

**Comment by jonathanrobie** [comment]
OK - thanks.  I will close the issue then.  Feel free to reopen it if needed.
