### ISSUE TITLE
Numbering of annotations.xml

### ISSUE THREAD

**Issue by jonathanrobie** [Clear-Bible/macula-hebrew#14]
The morphId column in annotations.xml uses Groves Center numbering.  It needs to be updated.

We need to decide whether to apply these annotations at the leaf Node level or at lower levels when we merge into the tree.  @rkjtan , any thoughts?

I think this should be orthogonal to `prepare-oshb`, it should be a separate merge.

**Comment by rkjtan** [comment]
My initial thought is that other attributes for specific morphemes seem to all be within the <m> element & that maybe putting these there may make sense. However, I would not be opposed to putting them at the leaf Node level if it makes better sense for data management & search purposes.

**Comment by klosoter** [comment]
I'll update the numbering (that needs to be done regardless of what we decide to do with the different level options).
