### ISSUE TITLE
The <p> element's text child should properly space the Hebrew words

### ISSUE THREAD

**Issue by ryderwishart** [Clear-Bible/macula-hebrew#37]
The Lowfat <p> element does not have proper spacing at the moment. For example, 

```xml
<p>
<milestone unit="verse" id="GEN 1:2">GEN 1:2</milestone>
וְ הָ אָ֗רֶץ הָיְתָ֥ה תֹ֨הוּ֙ וָ בֹ֔הוּ וְ חֹ֖שֶׁךְ עַל פְּנֵ֣י תְה֑וֹם וְ ר֣וּחַ אֱלֹהִ֔ים מְרַחֶ֖פֶת עַל פְּנֵ֥י הַ מָּֽיִם
</p>
```

- [ ] Correct spacing between sub-words

**Comment by pdurusau** [comment]
I don't know how the string is being constructed but it looks like each <w> element under <wg> is being reported as a spaced token. Concating the contents of all <w> elements under a <wg> with the same *reference,* ;-) here GEN 1:2!1, right to left, should give the desired result. Yes?
