### ISSUE TITLE
Inconsistencies with Marble Lexicon entries

### ISSUE THREAD

**Issue by klosoter** [Clear-Bible/macula-hebrew#44]
There are several inconsistencies with the Marble lexicon entries from `/ubsicap/marble-lexicon/SDBH/SDBH-EXPORT-en.XML`.

Please see the following files to check this out.
1. [macula-marble-mapping.xml](https://github.com/Clear-Bible/trees-oshb/blob/main/py/create-mappings/mappings/macula-marble-mapping.xml)
Mapping between macula trees `@morphId` and marble-BHS.
2. [oshb-marble-mapping.xml](https://github.com/Clear-Bible/trees-oshb/blob/main/py/create-mappings/mappings/oshb-marble-mapping.xml)
Mapping between macula trees `@n` and marble-BHS.
3. [marble-senses.xml](https://github.com/Clear-Bible/trees-oshb/blob/main/py/create-annotations-and-glosses/annotations-and-glosses/marble-senses.xml)
Glosses and LEXDomains grouped by marble-id extracted from [ubsicap](https://github.com/ubsicap/marble-lexicon)
4. [marble-issues.xml](https://github.com/Clear-Bible/trees-oshb/blob/main/py/create-annotations-and-glosses/annotations-and-glosses/issues/marble-issues.xml)

Collected issues with marble lexicon data. The following cases occur:

1. One marble sense corresponds to more than one Macula Node
```
<morph SDBH="עַקְרָב:001001002001006:Swarming Creatures:scorpion|עַקְרָב:003001010:Names of Locations:Ascent of Akrabbim;Ascent of Scorpions" marble-text="מַעֲלֵ֤ה עַקְרַבִּים֙">
  <Node n="060150030042" Cat="noun" morphId="060150030042" Unicode="מַעֲלֵ֤ה" nodeId="0601500300420010" StrongNumberX="4608" SenseNumber="1" Greek="προσαναβάσεως">
    <m word="JOS 15:3!4" n="060150030042" morph="Ncmsc" lang="H" lemma="4610+" after=" " pos="noun" type="common" gender="masculine" number="singular" state="construct" english="ascent" mandarin="隘口">מַעֲלֵ֤ה</m>
  </Node>
  <Node n="060150030051" Cat="noun" morphId="060150030051" Unicode="עַקְרַבִּים֙" nodeId="0601500300510010" StrongNumberX="6137" SenseNumber="2" Greek="ακραβιν">
    <m word="JOS 15:3!5" n="060150030051" lang="H" after=" " lemma="4610" morph="Np" pos="noun" type="proper" english="akrabbim" mandarin="亚克拉滨">עַקְרַבִּים֙</m>
  </Node>
</morph>
```
2. There are multiple lexicon entries that correspond to one Marble Id (see 4).
3. Of compounds both `<c>` elements and some of their `<m>` children are aligned with a marble sense (using the mapping), which results in duplicates:
```
<c english="Arameans of Beth-rehob" mandarin="伯·利合的亚兰人" SDBH="בֵּית רְחֹוב:003001010:Names of Locations:Beth-Rehob">
  <m USFMId="2SA 10:6!12" n="100100060121" lang="H" after=" " lemma="758" morph="Np" pos="noun" type="proper" SDBH="אֲרַם בֵּית־רְחֹוב:003001006:Names of Groups:Arameans of Beth-Rehob">אֲרַ֨ם</m>
  <m USFMId="2SA 10:6!13" n="100100060131" lang="H" after="־" lemma="1050+" morph="Np" pos="noun" type="proper">בֵּית</m>
  <m USFMId="2SA 10:6!14" n="100100060141" lang="H" after=" " lemma="1050" morph="Np" pos="noun" type="proper">רְח֜וֹב</m>
</c>
```
4. Sometimes, the lemma associated with a lexicon entry does not match the Hebrew word(s) that are associated with the reference id. See previous example, first `<m>` element. This can best be seen by checking the [marble-senses.xml](https://github.com/Clear-Bible/trees-oshb/blob/main/py/create-annotations-and-glosses/annotations-and-glosses/marble-senses.xml) which contains for each Marble Id:
- all associated lexicon entries with lemmas, glosses, and domains
- the Hebrew text corresponding to the id in the original Marble-BHS
Example (the `marble-text` being the text associated with the id in Marble-BHS):

```
<morph marble-id="00503300200046" marble-text="אשׁ" combined-data="אֵשׁ:001006006:Fire:fire|אֲשֵׁדָה:001005003:Landforms:slope|אֵשְׁדָּת::fiery law|דאה:002002001009:Move:to swoop down">
  <entry lemma="אֵשׁ" gloss="fire" domain="001006006:Fire"/>
  <entry lemma="אֲשֵׁדָה" gloss="slope" domain="001005003:Landforms"/>
  <entry lemma="אֵשְׁדָּת" gloss="fiery law" domain=""/>
  <entry lemma="דאה" gloss="to swoop down" domain="002002001009:Move"/>
</morph>
```

It is nearly impossible to just automatically select the entries for a given Id that match the actual Hebrew text because the lexicon lemmas are often base forms. So, there will probably be some sdbh senses that do not match the `<m>` or `<c>` attribute they are added to. 

Any thoughts, suggestions, or solutions?

**Comment by rkjtan** [comment]
It would seem that the fundamental issues are (1) some concepts/referents are represented by a phrase rather than a single word; (2) compounds are not recognized or represented in the same way by everyone. When one marble sense corresponds to more than one Macula Node (situation 1) or with compounds where both <c> elements and some of their <m> children are aligned with a marble sense (situation 3), can we just automatically map it to the higher MACULA phrase node that includes all relevant nodes? What would be the pros & cons of such a solution?
