### ISSUE TITLE
“Lemma” attribute in OSHB is really a pointer into an index that Open Scriptures created & need to pull in the actual lemma data

### ISSUE THREAD

**Issue by rkjtan** [Clear-Bible/macula-hebrew#5]
Ulrik's original proposal (which you can modify as needed) makes this need clear:

The OSHB trees are based on the Open Scriptures morphhb Hebrew Bible data. This data contains a “Lemma” attribute that is really a pointer into an index that Open Scriptures created. Each index entry ties together:

- An index into their version of the Brown Driver Briggs lexicon (BDB)
- The BDB lemma, with transliteration
- A gloss (<def>…</def>)
- A part of speech
- The Strong’s number
- A sub-division (aug) for the Strong’s number.
- TWOT number
- Information about the etymology as described by BDB

We should have the following:

- The id of the LexicalIndex entry. Call it LexicalIndexID
- The Hebrew BDB lemma (inside <w>…</w>). Call it BDBLemma
- The transliterated Hebrew BDB lemma (<w xlit=”…”>) Call it BDBLemmaXLit
- BDB entry index (<xref bdb=”…”>) Call it BDBId 
- The gloss. Call it OpenScripturesGloss

In addition, what is now the “Lemma” attribute should be renamed into “AugmentedStrongs”.

**Comment by RickBrannan** [comment]
OK, so am I doubling effort here? Happy to let @jcuenod integrate the OSHB index stuff.

**Comment by jcuenod** [comment]
I'm happy to do this, but I'm not sure what's in progress right now. @RickBrannan could you message me, or let me know who I should talk to?

**Comment by jacobwegner** [comment]
@RickBrannan No change to what you're working on; @jcuenod is not doing this.  I have a change happening to support a new feature we have on the frontend.

We're planning on replacing my change with the work that you're already working on.

Be happy to connect more on Slack tomorrow if useful!

**Comment by jcuenod** [comment]
Sorry for the misunderstanding.

**Comment by RickBrannan** [comment]
No, @jcuenod , the misunderstanding was my fault. I read you reviewing the PR as implementing the case. Thanks for following up and helping me better understand what was going on.
