### ISSUE TITLE
Extracting domain and senses from MARBLE OT

### ISSUE THREAD

**Issue by klosoter** [Clear-Bible/macula-hebrew#51]
See https://github.com/Clear-Bible/macula-greek/issues/21 for the same issue for Macula-Greek.

In Macula-Greek, we created two attributes:
- `domain="SubDomainNumber:DomainName:SubDomainName"`
- `sdbg="Lemma:EntryCode:Glosses`"

For the OT, we can't do the same:
- There is no `EntryCode` or any other unique identifier that points to a lexicon
- The domain data is problematic for multiple reasons.

## Problems with domain data in MARBLE SDBH

The domains are extracted from `SDBH-DOMAINS1.XML` and `SDBH-DOMAINS2.XML`

There are two sources that contain the entire lexicon:
1. `SDBH-01.XML` through `SDBH-23.XML`, which contain up-to-date full entries (multiple languages).
2. `SDBH-EXPORT-en.XML` which contains all English data from the full lexicon.

### Domains in the full lexicon
However, the first (most updated) source, have very minimal data on the domain. It only contains a category and a label for the lex domain and the core domain:
```xml
<LEXDomains>
    <LEXDomain>Parts: Vegetation</LEXDomain>
</LEXDomains>
<LEXCoreDomains>
    <LEXCoreDomain>Plant</LEXCoreDomain>
</LEXCoreDomains>
```
- the (core)domain identifier is missing
- the domain label does not correspond to the labels in the `SDBH-DOMAINS.XML`
- the domain label consists of the label of the last subdomain (which is very generic and not unique, e.g., "Kinship")

Conclusion: there is no way to find out to which specific domain they actually belong

### Domains in the English (exported) lexicon
The second source contains more information about the domain:
```xml
<LEXDomains>
    <LEXDomain>001003:Vegetation</LEXDomain>
</LEXDomains>
<LEXCoreDomains>
    <LEXCoreDomain>117:Plant</LEXCoreDomain>
</LEXCoreDomains>
```
- Both domains have identifiers here. The core domain id always consists of 3 characters (no subdomains, hence 'core domain') while the other domain can consist of up to 15 characters. 
- Again, only the label of the last domain is included.

### Additional Issues
There are a few more issues with the domain data:
1. The domain ids `001`, `002`, `003`, and `004` occur twice in the domains file, so they are not unique. The second occurrence is very general and does not have subdomains. However, this should not be a problem:
- the lexicon only refers to these 4 ids 8 times
- and always to the first occurrence of "001", that is the core domain `001:Objects`
However, looking up the domain using the identifier alone (without the domain label), will result in duplicates for these four ids. 

2. Some domain data (id + label) is preceded by a category indication that breaks up the usual format of "{domain id}:{domain label}":
```
['Valuable > Objects>001:Objects',
 'Valuable > Objects>001:Objects',
 'Speed > Move>002002001009:Move',
 'Shake > Non-Exist>002002002006:Non-Exist',
 'Shake > Move>002002001009:Move',
 'Shake > Afraid>002001002001:Afraid',
 'Shake > Afraid>002001002001:Afraid',
 'Valuable > Objects>001:Objects',
 'Shake > Afraid>002001002001:Afraid',
 'Shake > Afraid>002001002001:Afraid',
 'Shake > Afraid>002001002001:Afraid',
 'Shake > Afraid>002001002001:Afraid',
 'Intensity > Respect>002001002025:Respect',
 'Shake > Afraid>002001002001:Afraid',
 'Shake > Shame>002001002026:Shame',
 'Shake > Musical Instruments>001004001013:Musical Instruments',
 'Mix > Engage>002003003009:Engage',
 'Valuable > Objects>001:Objects',
 'Shake > Afraid>002001002001:Afraid',
 'Shake > Move>002002001009:Move',
 'Shake > Relief>002001002024:Relief',
 'Shake > Shame>002001002026:Shame',
 'Valuable > Objects>001:Objects',
 'Valuable > Objects>001:Objects',
 'Shake > Ready>002001002022:Ready',
 'Shake > Distress>002001002007:Distress',
 'Body > People>001001002003:People']
```

## Suggested Approach
1. We take the glosses, lemma, and domain from `SDBH-EXPORT-en.XML`
2. We remove the prefixed category indication mentioned in Additional issue 2: `Valuable > Objects>001:Objects` => `001:Objects`
3. We extend the domain label with all parent domain labels, like this:

![image](https://user-images.githubusercontent.com/61023061/173042297-44958da6-f1a4-4155-a6c5-37667998f532.png)

4. We also use the core domain and put it in the attribute like this: 
```xml 
<m domain="DomainID:DomainLabel:SubDomainLabel:..:SubDomainLabel:CoreDomainId:CoreDomainLabel" />
```

```xml
<m domain="001003:Objects:Vegetation:117:Plant"/m>
```

**Comment by klosoter** [comment]
Any ideas about this?

**Comment by klosoter** [comment]
Domains might become very long.

Also, it might be better if we make a separate attribute of subdomain

**Comment by jonathanrobie** [comment]
First off, SDBG and SDBH do have different ontologies for semantic domains.  

I generally like your approach, but perhaps we don't need to reproduce the full hierarchy for each instance.  I think I prefer to use just this:

![image](https://user-images.githubusercontent.com/1767869/174097663-fca34c75-d195-46ed-a6df-29bb0c08a860.png)

Not all of this:

![image](https://user-images.githubusercontent.com/1767869/174097786-4c9d949b-80ed-48aa-8565-86c177ebf4c9.png)

And I also think we should put the domain map from the first window in a JSON structure under sources.

**Comment by jonathanrobie** [comment]
The domain numbers are hierarchical, so if you have a 9 digit domain number, you can strip off the rightmost 3 digits to find the parent.   I don't think we have to reproduce the hierarchy in each instance.

**Comment by klosoter** [comment]
so 

```xml
<m domain="DomainID:lastDomainName:coreDomainID:lastCoreDomainName">
```

**Comment by klosoter** [comment]
This way, there are also 2 or 4 attribute elements in fixed positions

**Comment by klosoter** [comment]
> Domains are not always clean (following the same format of Number:Name). Example
> 
> ```
> 002001001028:Good>002001002017:Just
> ```
> 
> When expanding the domain names, it becomes:
> 
> ```
> 002004002013:Events:Perception:Cognition:Test>002001002017:Events:Description:Attitude:Just
> ```
> 
> What do we do about this?
> 
> We could separate the two:
> 
> ```
> 002004002013:Events:Perception:Cognition:Test|002001002017:Events:Description:Attitude:Just
> ```
> 
> But it should remain clear that these belong to one entry (that corresponds to the entry at the same position in the `sdbh` attribute). So we would have to use a different delimiter than the one used to separate entries.

What about this, though?

I don't think we lose much if we interpret ">" as two different domains for one entry (i.e., separating them by a delimiter like ";")
