### ISSUE TITLE
Add lemmas to Hebrew nodes trees 

### ISSUE THREAD

**Issue by ryderwishart** [Clear-Bible/macula-hebrew#64]
We have strongs numbers as `@lemma`, and we should be pulling in the actual lemmas. 

Jonathan mentioned something about using strongs data from our OSHB data.

**Comment by jonathanrobie** [comment]
The TSV always reflects what's in the trees.  The bigger step is getting the lemmas into the trees.

**Comment by ryderwishart** [comment]
For future reference, this [file](https://github.com/openscriptures/HebrewLexicon/blob/master/AugIndex.xml) maps the augmented Strongs numbers in our `@lemma` to the entries in this [lexical index](https://github.com/openscriptures/HebrewLexicon/blob/master/LexicalIndex.xml), which has the roots.

**Comment by ryderwishart** [comment]
Cf. #5
